server:
  port: 8082

spring:
  application:
    name: putnici-resource-server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      h2:
        console:
          enabled: true

security:
  oauth2:
    resource:
      token-info-uri: http://auth-service:8080/oauth/check_token

    client:
      client-id: putnici-resource-client
      client-secret: putnici-resource-secret
      authorized-grant-type: password
      accessTokenUri: http://auth-service:8080/oauth/token


