apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: travel-agency-auth-service
  name: travel-agency-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: travel-agency-auth-service
  template:
    metadata:
      labels:
        io.kompose.service: travel-agency-auth-service
    spec:
      containers:
      - env:
        - name: RDS_DB_NAME
          value: travelagencyauth
        - name: RDS_HOSTNAME
          value: mysql
        - name: RDS_PASSWORD
          value: vladatravelagencyauth
        - name: RDS_PORT
          value: "3306"
        - name: RDS_USERNAME
          value: travelagencyauth-user
        image: exxperiment899/walter-auth-service:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: travel-agency-auth-service
        ports:
        - containerPort: 8080
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
