version: '3.7'
services:
  travel-agency-auth-service:
    image: exxperiment899/walter-auth-service:0.0.1-SNAPSHOT
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: travelagencyauth
      RDS_USERNAME: travelagencyauth-user
      RDS_PASSWORD: vladatravelagencyauth

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: vladapassword
      MYSQL_USER: travelagencyauth-user
      MYSQL_PASSWORD: vladatravelagencyauth
      MYSQL_DATABASE: travelagencyauth
    volumes:
      - mysql-database-data-volume:/var/lib/mysql

# Volumes
volumes:
  mysql-database-data-volume:
